### PR TITLE
Created 404 Page, Restructuring, updated routers

### PR DESCRIPTION
**Pull request by xchrisbradley**
Created 404 Page:
- For the most part, it works well, if you go to a random page `http://localhost:3000/ddff/dada` it will display the error message. It looks funky for the footer until we can update and move the contents to the layout folder
- I suggest updating the message unless you want to keep it for kicks!

Restructuring:
- Did more restructuring, still have to move your current `components` contents to either the `modules` or `layout` depending on what it is doing.

Routes:
- I'm used to the `exact` route to be able to handle incorrect requests made to the web app, but if you don't we can change back.

Removed the test file and created a `tests` folder where once test begin, they are more structured.

Removed the webvitals, thinking of adding that to the index file as well as some other handy functionality.

Notes:
- You'll notice I used react components vs a function, they logically arent that different I'm just used to the class-based way. I can change back if that's your preference though!

### CODE REVIEW

**Comment by xchrisbradley** [comment]
The background got changed to white on the homepage, this is temporary until I move the other components into their right folders.

If you want me to fix it now before completing the PR just lmk.

**Comment by leplerjacob** [comment]
Thanks @bradleycm . I am taking a look now...seems good so far. I did prefer functional. But I think we can stick to class based since that is what you're used to. It would be a learning experience for me since I haven't use React Component much. Thank you

**Comment by leplerjacob** [comment]
@bradleycm I see. So eventually we'd move the components over to shared in modules, or to layout folder. I am not too sure what is meant by layout. But I'll look this up.

**Comment by xchrisbradley** [comment]
Yea with angular it's more strict, using react is basically free form and up to you.

I suggested this approach as I didn't  see one already in place, maybe we can create a docs folder and add a CONTRIBUTING.md that outlines the structure of the project as well as best practices i.e (should we use functional components or the class-based components)

**Pull request merged**
